import assert from "node:assert/strict";
import { mkdir, readFile, writeFile, utimes } from "node:fs/promises";
import { join } from "node:path";
import { mock } from "bun:test";
import { application, waitFor } from "../../src/core/lifecycle.ts";
let runs = 0, active = 0, peak = 0, release: (() => void) | undefined, hold = false;
mock.module("../../src/agent/python-toolchain.ts", () => ({ ensureDocumentToolchain: async () => true, venvPythonPath: () => "fixture-python" }));
mock.module("../../src/core/process.ts", () => ({ runProcess: async (options: any) => {
  runs++; active++; peak = Math.max(peak, active);
  try {
    assert.equal(options.command, "fixture-python");
    if (hold) await waitFor(new Promise<void>(resolve => { release = resolve; }), options.signal);
    options.signal.throwIfAborted();
    const text = await readFile(options.args[1], "utf8");
    await writeFile(options.args[3], text);
    return { exitCode: 0, output: JSON.stringify({ units: 1, characters: text.length, truncated: false }) };
  } finally { active--; }
} }));
const { extractDocument } = await import("../../src/agent/document-extract.ts");
const root = process.cwd(), workspace = join(root, "workspace"), index = join(root, "index"), a = join(root, "user-a"), b = join(root, "user-b");
await Promise.all([workspace, index, a, b].map(path => mkdir(path)));
const options = (tempDir: string) => ({ workspaceDir: workspace, tempDir, indexPath: join(index, "materials.md"), venvDir: join(root, "venv") });
const source = join(workspace, "shared.docx");
await writeFile(source, "alpha");
const first = await extractDocument(options(a), source);
assert.equal(first.cacheHit, false); assert.equal(runs, 1);
const hit = await extractDocument(options(b), source);
assert.equal(hit.cacheHit, true); assert.equal(hit.path, first.path); assert.equal(runs, 1);
await writeFile(join(workspace, "renamed.docx"), "alpha");
assert.equal((await extractDocument(options(a), join(workspace, "renamed.docx"))).path, first.path);
await writeFile(source, "bravo");
await utimes(source, new Date(0), new Date(0));
const changed = await extractDocument(options(a), source);
assert.equal(changed.cacheHit, false); assert.notEqual(changed.path, first.path);
await writeFile(changed.path, "tampered");
assert.equal((await extractDocument(options(a), source)).cacheHit, false);
assert.equal(await readFile(changed.path, "utf8"), "bravo");
assert.notEqual((await extractDocument(options(a), source, 1000)).path, changed.path);
await writeFile(join(a, "private.docx"), "alpha"); await writeFile(join(b, "private.docx"), "alpha");
const privateA = await extractDocument(options(a), join(a, "private.docx"));
const privateB = await extractDocument(options(b), join(b, "private.docx"));
assert.notEqual(privateA.path, privateB.path);
assert.ok(privateA.path.startsWith(a)); assert.ok(privateB.path.startsWith(b));
await assert.rejects(extractDocument(options(a), join(b, "private.docx")), /只能解析/);
await writeFile(source, "shared in flight");
hold = true;
const abort = new AbortController(), before = runs;
const p1 = extractDocument(options(a), source, undefined, abort.signal).then(() => false, () => true);
const p2 = extractDocument(options(b), source);
while (runs === before) await Bun.sleep(5);
await Bun.sleep(30); abort.abort();
assert.equal(await p1, true);
hold = false; release!();
assert.equal((await p2).cacheHit, false); assert.equal(runs, before + 1);
await writeFile(source, "only consumer cancels");
hold = true;
const alone = new AbortController(), previous = runs;
const cancelled = extractDocument(options(a), source, undefined, alone.signal).then(() => false, () => true);
while (runs === previous) await Bun.sleep(5);
alone.abort(); assert.equal(await cancelled, true);
await application.drain(); assert.equal(active, 0);
hold = false;
assert.equal((await extractDocument(options(a), source)).cacheHit, false);
// Semaphore applies across different documents, not only the shared-key flight.
await Promise.all(Array.from({ length: 5 }, async (_, n) => {
  const path = join(workspace, "parallel-" + n + ".docx"); await writeFile(path, "document-" + n);
  await extractDocument(options(a), path);
}));
assert.ok(peak <= 2);
await application.drain();
console.log("DOCUMENT_CACHE_PASSED");
